logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"  # Custom console log pattern
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"    # Custom file log pattern
  file:
    name: ./logs/event-discovery.log
  level:
    io.debezium: INFO
    io.debezium.connector: INFO
    io.debezium.connector.postgresql: INFO
    root: INFO
    org:
      springframework:
        web: INFO
        data: INFO
        security: INFO
        boot: INFO
        cloud: INFO
        kafka: INFO
        jpa: INFO
        hibernate: INFO
        ehcache: INFO
        quartz: INFO
